version: "3.8"

volumes:
  db_data:
  cache_data:

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data    
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env.dev
  
  cache:
    image: redis:${REDIS_VERSION}
    restart: always
    env_file:
      - .env.dev
    expose:
      - "${REDIS_PORT}"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - cache_data:/data
      
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c ./docker-entrypoint.dev.sh
    volumes:
      - .:/app
    env_file:
      - .env.dev 
    ports:
      - "${APP_PORT}:${APP_PORT}"    
    depends_on:
      - db
      - cache

